// frontend/src/lib/features/dashboard/user-info-card.svelte
<script lang="ts">
	import { createRequestVerification } from '$lib/api/email-verification/email-verification';
	import type { UserPublic } from '$lib/api/superimpress.schemas';
	import Button from '$lib/components/ui/button.svelte';
	import { getErrorMessage } from '$lib/utils/get-error-message';

	type Props = {
		user: UserPublic;
	};

	let { user }: Props = $props();

	const verificationRequest = createRequestVerification();
</script>

<div class="card w-full max-w-md bg-base-200 shadow-xl">
	<div class="card-body">
		<h2 class="card-title">User Information</h2>

		<div class="divider"></div>

		<div class="space-y-4">
			<div class="flex flex-col">
				<span class="text-sm font-semibold text-base-content/70">Email</span>
				<div class="flex items-center justify-between">
					<span class="text-lg" data-testid="user-email">{user.email}</span>
					{#if user.email_verified}
						<div class="badge badge-sm badge-success">Verified</div>
					{:else}
						<div class="badge badge-sm badge-warning">Not Verified</div>
					{/if}
				</div>
			</div>

			<div class="flex flex-col">
				<span class="text-sm font-semibold text-base-content/70">User ID</span>
				<span class="font-mono text-lg" data-testid="user-id">{user.id}</span>
			</div>

			{#if !user.email_verified}
				<div class="mt-4">
					<Button
						class="w-full"
						disabled={verificationRequest.isPending}
						variant="outline"
						onclick={() => verificationRequest.mutate()}
					>
						{#if verificationRequest.isPending}
							<span class="loading loading-sm loading-spinner"></span>
							Sending...
						{:else}
							Verify Email
						{/if}
					</Button>

					{#if verificationRequest.isSuccess}
						<div class="mt-2 text-sm text-green-600">
							Verification email sent to {verificationRequest.data.email}
						</div>
					{/if}

					{#if verificationRequest.isError}
						<div class="mt-2 text-sm text-error" role="alert">
							{getErrorMessage(verificationRequest.error)}
						</div>
					{/if}
				</div>
			{/if}
		</div>
	</div>
</div>

// frontend/src/features/dashboard/user-info-card.tsx
import type { UserPublic } from '@/api/superimpress.schemas';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { AlertCircle } from 'lucide-react';

export default function UserInfoCard({ user }: { user: UserPublic }) {
	return (
		<Card className="max-w-md">
			<CardHeader>
				<CardTitle>User Information</CardTitle>
				<CardDescription>Your account details</CardDescription>
			</CardHeader>
			<CardContent className="space-y-4">
				<div className="grid grid-cols-[100px_1fr] gap-2 text-sm">
					<span className="font-medium text-muted-foreground">ID:</span>
					<span>{user.id}</span>

					<span className="font-medium text-muted-foreground">Email:</span>
					<span>{user.email}</span>

					<span className="font-medium text-muted-foreground">Verified:</span>
					<span>
						{user.email_verified ? (
							<span className="font-medium text-green-600">Yes</span>
						) : (
							<span className="font-medium text-yellow-600">No</span>
						)}
					</span>
				</div>
			</CardContent>
		</Card>
	);
}

export function UserInfoCardLoading() {
	return (
		<Card className="max-w-md">
			<CardHeader>
				<CardTitle>User Information</CardTitle>
				<CardDescription>Your account details</CardDescription>
			</CardHeader>
			<CardContent className="space-y-4">
				<div className="grid grid-cols-[100px_1fr] gap-2 text-sm">
					<span className="font-medium text-muted-foreground">ID:</span>
					<Skeleton className="h-5 w-full" />

					<span className="font-medium text-muted-foreground">Email:</span>
					<Skeleton className="h-5 w-full" />

					<span className="font-medium text-muted-foreground">Verified:</span>
					<Skeleton className="h-5 w-20" />
				</div>
			</CardContent>
		</Card>
	);
}

export function UserInfoCardError() {
	return (
		<Card className="max-w-md border-destructive/50">
			<CardHeader>
				<CardTitle>User Information</CardTitle>
				<CardDescription>Error loading details</CardDescription>
			</CardHeader>
			<CardContent className="justify-centertext-center flex flex-col items-center">
				<AlertCircle className="mb-2 size-8 text-destructive" />
				<p className="text-sm font-medium text-muted-foreground">Failed to load user information</p>
			</CardContent>
		</Card>
	);
}
