// frontend/src/features/auth/register/register.tsx
import { useRegisterUser } from '@/api/authentication/authentication';
import { Button } from '@/components/ui/button';
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle
} from '@/components/ui/card';
import { Field, FieldError, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { AuthLayout } from '@/layouts/auth-layout';
import { getErrorMessage } from '@/utils/get-error-message';
import { useForm } from '@tanstack/react-form';
import { Link, useNavigate } from '@tanstack/react-router';
import { useState } from 'react';
import * as z from 'zod';

const formSchema = z
	.object({
		email: z.email('Invalid email address'),
		password: z
			.string()
			.min(8, 'Password must be at least 8 characters')
			.max(15, 'Password must be at most 15 characters'),
		confirmPassword: z.string()
	})
	.refine((data) => data.password === data.confirmPassword, {
		message: 'Passwords do not match',
		path: ['confirmPassword']
	});

export default function Register() {
	const [error, setError] = useState<string | null>(null);

	const navigate = useNavigate();
	const { mutate, isPending } = useRegisterUser();

	const form = useForm({
		defaultValues: {
			email: '',
			password: '',
			confirmPassword: ''
		},
		validators: {
			onSubmit: formSchema
		},
		onSubmit: async ({ value }) => {
			setError(null);
			mutate(
				{
					data: {
						email: value.email,
						password: value.password
					}
				},
				{
					onSuccess: () => {
						navigate({ to: '/login' });
					},
					onError: (error) => {
						setError(getErrorMessage(error));
					}
				}
			);
		}
	});

	return (
		<AuthLayout>
			<Card>
				<CardHeader>
					<CardTitle>Create Account</CardTitle>
					<CardDescription>Enter your details to create a new account</CardDescription>
				</CardHeader>

				<CardContent>
					<form
						id="register-form"
						onSubmit={(e) => {
							e.preventDefault();
							form.handleSubmit();
						}}
					>
						<fieldset disabled={isPending} className="space-y-4">
							<FieldGroup>
								<form.Field
									name="email"
									children={(field) => {
										const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid;
										return (
											<Field data-invalid={isInvalid}>
												<FieldLabel htmlFor="email">Email</FieldLabel>
												<Input
													id="email"
													name="email"
													type="email"
													autoComplete="email"
													required
													value={field.state.value}
													onChange={(e) => field.handleChange(e.target.value)}
													onBlur={field.handleBlur}
													aria-invalid={isInvalid}
												/>
												{isInvalid && <FieldError errors={field.state.meta.errors} />}
											</Field>
										);
									}}
								/>
								<form.Field
									name="password"
									children={(field) => {
										const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid;
										return (
											<Field data-invalid={isInvalid}>
												<FieldLabel htmlFor="password">Password</FieldLabel>
												<Input
													id="password"
													name="password"
													type="password"
													autoComplete="new-password"
													required
													minLength={8}
													maxLength={15}
													value={field.state.value}
													onChange={(e) => field.handleChange(e.target.value)}
													onBlur={field.handleBlur}
													aria-invalid={isInvalid}
												/>
												<p className="text-xs text-muted-foreground">
													Must be 8-15 characters with uppercase, lowercase, digit, and special
													character
												</p>
												{isInvalid && <FieldError errors={field.state.meta.errors} />}
											</Field>
										);
									}}
								/>
								<form.Field
									name="confirmPassword"
									children={(field) => {
										const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid;
										return (
											<Field data-invalid={isInvalid}>
												<FieldLabel htmlFor="confirmPassword">Confirm Password</FieldLabel>
												<Input
													id="confirmPassword"
													name="confirmPassword"
													type="password"
													autoComplete="new-password"
													required
													minLength={8}
													maxLength={15}
													value={field.state.value}
													onChange={(e) => field.handleChange(e.target.value)}
													onBlur={field.handleBlur}
													aria-invalid={isInvalid}
												/>
												{isInvalid && <FieldError errors={field.state.meta.errors} />}
											</Field>
										);
									}}
								/>
							</FieldGroup>

							{error && (
								<div
									role="alert"
									className="rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive"
								>
									{error}
								</div>
							)}

							<Button type="submit" className="w-full" aria-busy={isPending}>
								{isPending ? 'Creating account...' : 'Create Account'}
							</Button>
						</fieldset>
					</form>
				</CardContent>

				<CardFooter className="justify-center">
					<div className="text-center text-sm">
						<span className="text-muted-foreground">Already have an account? </span>
						<Link to="/login" className="font-medium text-primary hover:underline">
							Sign in
						</Link>
					</div>
				</CardFooter>
			</Card>
		</AuthLayout>
	);
}

// frontend/src/lib/features/auth/register/register.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import Input from '$lib/components/ui/input.svelte';
	import Label from '$lib/components/ui/label.svelte';
	import AuthLayout from '$lib/layouts/auth-layout.svelte';
	import { cn } from '$lib/utils/cn';
	import { createForm } from '@tanstack/svelte-form';
	import { createMutation } from '@tanstack/svelte-query';
	import z from 'zod';
	import FieldInfo from '../field-info.svelte';
	import { registerApi } from './api';

	const registerFormSchema = z
		.object({
			email: z.email('Invalid email address').trim(),
			password: z.string().trim().min(1, 'Password is required'),
			confirmPassword: z.string()
		})
		.refine((data) => data.password === data.confirmPassword, {
			error: 'Passwords do not match',
			path: ['confirmPassword']
		});

	const registerMutation = createMutation(() => ({
		mutationFn: registerApi,
		onSuccess: () => {
			goto(resolve('/login'));
		}
	}));

	const form = createForm(() => ({
		defaultValues: {
			email: '',
			password: '',
			confirmPassword: ''
		},
		validators: { onSubmit: registerFormSchema },
		onSubmit: async ({ value }) => {
			registerMutation.mutate(value);
		}
	}));
</script>

<AuthLayout>
	<h1 class="sr-only text-xl">Register</h1>

	<form
		onsubmit={(e) => {
			e.preventDefault();
			e.stopPropagation();
			form.handleSubmit();
		}}
		class="my-4"
		aria-labelledby="form-heading"
	>
		<fieldset
			class="fieldset w-xs rounded-box border border-base-300 bg-base-200 p-4"
			disabled={registerMutation.isPending}
		>
			<legend id="form-heading" class="fieldset-legend">Create your account</legend>

			<form.Field name="email">
				{#snippet children(field)}
					<Label for={field.name}>Email</Label>
					<Input
						id={field.name}
						name={field.name}
						value={field.state.value}
						type="email"
						class={cn(field.state.meta.isTouched && !field.state.meta.isValid && 'input-error')}
						aria-invalid={field.state.meta.isTouched && !field.state.meta.isValid}
						autocomplete="email"
						onchange={(e) => {
							const target = e.target as HTMLInputElement;
							field.handleChange(target.value);
						}}
					/>

					<FieldInfo {field} />
				{/snippet}
			</form.Field>

			<form.Field name="password">
				{#snippet children(field)}
					<Label for={field.name}>Password</Label>
					<Input
						id={field.name}
						name={field.name}
						value={field.state.value}
						type="password"
						class={cn(field.state.meta.isTouched && !field.state.meta.isValid && 'input-error')}
						aria-invalid={field.state.meta.isTouched && !field.state.meta.isValid}
						autocomplete="new-password"
						onchange={(e) => {
							const target = e.target as HTMLInputElement;
							field.handleChange(target.value);
						}}
					/>

					<FieldInfo {field} />
				{/snippet}
			</form.Field>

			<form.Field name="confirmPassword">
				{#snippet children(field)}
					<Label for={field.name}>Confirm password</Label>
					<Input
						id={field.name}
						name={field.name}
						value={field.state.value}
						type="password"
						class={cn(field.state.meta.isTouched && !field.state.meta.isValid && 'input-error')}
						aria-invalid={field.state.meta.isTouched && !field.state.meta.isValid}
						autocomplete="new-password"
						onchange={(e) => {
							const target = e.target as HTMLInputElement;
							field.handleChange(target.value);
						}}
					/>

					<FieldInfo {field} />
				{/snippet}
			</form.Field>

			<button type="submit" class="btn mt-4 btn-neutral" aria-busy={registerMutation.isPending}>
				{registerMutation.isPending ? 'Registering...' : 'Register'}
			</button>

			{#if registerMutation.isError}
				<em role="alert" class="text-sm text-error" aria-live="polite" id="error-message">
					{registerMutation.error?.message}
				</em>
			{/if}
		</fieldset>
	</form>

	<p>
		Already have an account?
		<a href={resolve('/login')} class="link" data-sveltekit-preload-data>Log in</a>
	</p>
</AuthLayout>
