// frontend/src/layouts/app-layout.tsx
import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';

export default function AppLayout({ children }: { children: React.ReactNode }) {
	return (
		<SidebarProvider>
			<AppSidebar />
			<main className="w-full space-y-4 p-4">
				<SidebarTrigger />
				<div>{children}</div>
			</main>
		</SidebarProvider>
	);
}

// frontend/src/lib/layouts/app-layout.svelte
<script lang="ts">
	import AppSidebar from '$lib/components/app-sidebar.svelte';

	let { children } = $props();
</script>

<div class="flex h-svh w-full bg-base-100">
	<AppSidebar />

	<div class="flex flex-1 flex-col overflow-hidden">
		<main class="flex-1 overflow-y-auto p-8">
			{@render children?.()}
		</main>
	</div>
</div>
