// frontend/src/routes/register/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';

	let email = '';
	let password = '';
	let confirmPassword = '';
	let errorMessage = '';
	let successMessage = '';
	let isSubmitting = false;

	async function handleSubmit(event: Event) {
		event.preventDefault();
		errorMessage = '';
		successMessage = '';

		// Client-side validation
		if (!email || !password || !confirmPassword) {
			errorMessage = 'All fields are required';
			return;
		}

		if (password !== confirmPassword) {
			errorMessage = 'Passwords do not match';
			return;
		}

		if (password.length < 8) {
			errorMessage = 'Password must be at least 8 characters long';
			return;
		}

		isSubmitting = true;

		try {
			const response = await fetch('/api/register', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({ email, password })
			});

			if (!response.ok) {
				const data = await response.json();
				errorMessage = data.detail || 'Registration failed';
				return;
			}

			const data = await response.json();
			successMessage = `Registration successful! Welcome, ${data.email}`;

			// Clear form
			email = '';
			password = '';
			confirmPassword = '';
		} catch {
			errorMessage = 'An error occurred. Please try again.';
		} finally {
			isSubmitting = false;
		}
	}
</script>

<main class="container space-y-4 p-10">
	<h1 class="text-xl">Register</h1>

	<form on:submit={handleSubmit} aria-labelledby="form-heading">
		<fieldset class="space-y-2" disabled={isSubmitting}>
			<legend id="form-heading">Create your account</legend>

			<div>
				<label for="email">
					Email address
					<input
						type="email"
						id="email"
						name="email"
						class="border"
						bind:value={email}
						required
						autocomplete="email"
						aria-required="true"
						aria-describedby={errorMessage ? 'error-message' : undefined}
					/>
				</label>
			</div>

			<div>
				<label for="password">
					Password
					<input
						type="password"
						id="password"
						name="password"
						class="border"
						bind:value={password}
						required
						autocomplete="new-password"
						aria-required="true"
						aria-describedby={errorMessage ? 'error-message' : undefined}
					/>
				</label>
			</div>

			<div>
				<label for="confirm-password">
					Confirm password
					<input
						type="password"
						id="confirm-password"
						name="confirm-password"
						class="border"
						bind:value={confirmPassword}
						required
						autocomplete="new-password"
						aria-required="true"
						aria-describedby={errorMessage ? 'error-message' : undefined}
					/>
				</label>
			</div>

			<button type="submit" class="border px-2 py-1" aria-busy={isSubmitting}>
				{isSubmitting ? 'Registering...' : 'Register'}
			</button>
		</fieldset>
	</form>

	{#if errorMessage}
		<div role="alert" aria-live="polite" id="error-message">
			<p><strong>Error:</strong> {errorMessage}</p>
		</div>
	{/if}

	{#if successMessage}
		<div role="status" aria-live="polite" id="success-message">
			<p>{successMessage}</p>
		</div>
	{/if}

	<p>
		Already have an account?
		<a href={resolve('/login')} class="underline" data-sveltekit-preload-data>Log in</a>
	</p>
</main>

// frontend/src/features/auth/register/register.tsx
import { useRegisterUser } from '@/api/authentication/authentication';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { AuthLayout } from '@/layouts/auth-layout';
import { getErrorMessage } from '@/utils/get-error-message';
import { Link, useNavigate } from '@tanstack/react-router';
import type { AxiosError } from 'axios';
import { useState } from 'react';

export default function Register() {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [confirmPassword, setConfirmPassword] = useState('');
	const [error, setError] = useState<string | null>(null);

	const navigate = useNavigate();
	const { mutate, isPending } = useRegisterUser();

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();
		setError(null);

		// Client-side validation
		if (password !== confirmPassword) {
			setError('Passwords do not match');
			return;
		}

		mutate(
			{
				data: {
					email,
					password
				}
			},
			{
				onSuccess: () => {
					navigate({ to: '/login' });
				},
				onError: (error) => {
					setError(getErrorMessage(error as AxiosError));
				}
			}
		);
	};

	return (
		<AuthLayout>
			<div className="space-y-6">
				<div className="space-y-2 text-center">
					<h1 className="text-2xl font-bold">Create Account</h1>
					<p className="text-sm text-muted-foreground">
						Enter your details to create a new account
					</p>
				</div>

				<form onSubmit={handleSubmit} className="space-y-4">
					<fieldset disabled={isPending} className="space-y-4">
						<div className="space-y-2">
							<Label htmlFor="email">Email</Label>
							<Input
								id="email"
								name="email"
								type="email"
								autoComplete="email"
								required
								value={email}
								onChange={(e) => setEmail(e.target.value)}
								aria-invalid={!!error}
							/>
						</div>

						<div className="space-y-2">
							<Label htmlFor="password">Password</Label>
							<Input
								id="password"
								name="password"
								type="password"
								autoComplete="new-password"
								required
								minLength={8}
								maxLength={15}
								value={password}
								onChange={(e) => setPassword(e.target.value)}
								aria-invalid={!!error}
							/>
							<p className="text-xs text-muted-foreground">
								Must be 8-15 characters with uppercase, lowercase, digit, and special character
							</p>
						</div>

						<div className="space-y-2">
							<Label htmlFor="confirmPassword">Confirm Password</Label>
							<Input
								id="confirmPassword"
								name="confirmPassword"
								type="password"
								autoComplete="new-password"
								required
								minLength={8}
								maxLength={15}
								value={confirmPassword}
								onChange={(e) => setConfirmPassword(e.target.value)}
								aria-invalid={!!error}
							/>
						</div>

						{error && (
							<div
								role="alert"
								className="rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive"
							>
								{error}
							</div>
						)}

						<Button type="submit" className="w-full" aria-busy={isPending}>
							{isPending ? 'Creating account...' : 'Create Account'}
						</Button>
					</fieldset>
				</form>

				<div className="text-center text-sm">
					<span className="text-muted-foreground">Already have an account? </span>
					<Link to="/login" className="font-medium text-primary hover:underline">
						Sign in
					</Link>
				</div>
			</div>
		</AuthLayout>
	);
}
